VIRTUAL_WIDTH = 130
VIRTUAL_HEIGHT = 300

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 850

BASKET_SPEED = 150

TILE_SIZE = 16

SCREEN_WIDTH = (VIRTUAL_WIDTH / TILE_SIZE) + 16
SCREEN_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) + 16

